<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an optionDemoTest</name>
   <tag></tag>
   <elementGuidId>a0b230e9-1ce3-48ee-9373-556b0b283756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gwt-debug-subProject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-subProject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-subProject</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>464befb8-2fd9-420a-86ec-2eef4151f2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-mandatory c-simple-ddl c-simple-ddl-width</value>
      <webElementGuid>b895a0c1-0a30-4541-9b33-9148250315f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-subProject</value>
      <webElementGuid>eb2aea53-d8eb-41cb-acb3-e050213cd6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an optionDemoTest</value>
      <webElementGuid>9f0e4e55-29ea-4211-9325-3298dfd843d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-subProject&quot;)</value>
      <webElementGuid>991c1006-2c93-4b59-a4d9-8b171dfafc74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gwt-debug-subProject']</value>
      <webElementGuid>5d7a5cf4-a84e-4b36-a35f-8614a10a4200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>d3adf352-df4a-446e-a4bb-5fcae23aa5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Project'])[1]/following::select[1]</value>
      <webElementGuid>29d9d0b5-4b3c-4415-9bfd-a9ca28cc63de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have selected a test server to publish.'])[1]/following::select[1]</value>
      <webElementGuid>97ad4ecb-d476-41e6-a5b9-e0642f32f57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[2]/preceding::select[1]</value>
      <webElementGuid>efa77a34-77fa-4313-a69a-ad90fe009de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Type'])[1]/preceding::select[2]</value>
      <webElementGuid>79f738b7-373a-42a0-9e92-e5cf4079b0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>30579148-610e-4a0b-965f-10120d0e12d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gwt-debug-subProject' and (text() = 'Select an optionDemoTest' or . = 'Select an optionDemoTest')]</value>
      <webElementGuid>a4c18473-0a86-4085-8642-899fd0755e20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
