<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6e946b7a-974b-42b1-bbcc-6af1154fd459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-liveRadioStyle > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gwt-debug-liveRadioStyle']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-liveRadioStyle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>20655e46-8054-4d6c-8799-497c2c594cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>skin/img/radio_chk0.gif</value>
      <webElementGuid>f5b32c14-fcaa-44e4-bc95-b658732121c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-liveRadioStyle&quot;)/img[1]</value>
      <webElementGuid>757a987d-5742-418a-a3ab-e9732ad4dacd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='gwt-debug-liveRadioStyle']/img</value>
      <webElementGuid>dfdc8c72-c1be-4c1a-b7a6-a8f926c5d012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>be39eb6f-059a-45f5-a6b8-045567468e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'skin/img/radio_chk0.gif']</value>
      <webElementGuid>239d98aa-490d-42f5-b644-1eb32aad5782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
