<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_App Server URL_gwt-uid-168</name>
   <tag></tag>
   <elementGuidId>5ab80a9e-07c3-4264-a58f-295a9021d2ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-uid-168</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox' and @id = 'gwt-uid-168']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Master for external reference data&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfb777e2-33fe-4a69-b546-f4a3b2257ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7542024e-f52a-491c-abd4-6e53dc197bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d7328434-8e9f-4c58-9533-d360d61844b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-uid-168</value>
      <webElementGuid>e2761074-e6c2-4d84-b63e-259f0d79509c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4d3819c6-eb0e-4211-aedf-e70c8bca90e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-uid-168&quot;)</value>
      <webElementGuid>098595a3-b5a6-461d-870a-876c68a23d11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gwt-uid-168']</value>
      <webElementGuid>862e6cbe-d05e-4101-a5f9-09e89cac48b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>3fa8f5cd-41d4-4bb3-b359-b52db6ec1a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'gwt-uid-168']</value>
      <webElementGuid>a998cfd3-a20e-457b-a690-d0be2946a34c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
