<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_gwt-debug-</name>
   <tag></tag>
   <elementGuidId>a9ee27f2-2b14-41a4-9275-eed91e737a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c-bottom-margin > div > div > #gwt-debug-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//div/*[text()='${label}']//following::div//input[@id='gwt-debug-'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;cpm-whole-body&quot;]/div[@class=&quot;popupPanel&quot;]/div[1]/table[1]/tbody[1]/tr[@class=&quot;dialogMiddle&quot;]/td[@class=&quot;dialogMiddleCenter&quot;]/div[@class=&quot;dialogMiddleCenterInner dialogContent&quot;]/div[@class=&quot;targetPopup&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;c-bottom-margin&quot;]/div[1]/div[1]/input[@id=&quot;gwt-debug-&quot;][count(. | //*[@type = 'text' and @id = 'gwt-debug-']) = count(//*[@type = 'text' and @id = 'gwt-debug-'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62e2977a-276f-4f8a-8da3-3bbb97b2866b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0383a6ae-ce5f-492f-8654-2e47ab0f2f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-textbox c-mandatory</value>
      <webElementGuid>c25316f9-de2e-4be0-a84d-3c4ae4c3f578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-</value>
      <webElementGuid>9bf2fcff-76cf-4bfb-9912-2093cbd85c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>4de62c3f-6104-484d-91e4-3a78eb6ae28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b693d772-1386-42a1-aacb-2807aebc3866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cpm-whole-body&quot;]/div[@class=&quot;popupPanel&quot;]/div[1]/table[1]/tbody[1]/tr[@class=&quot;dialogMiddle&quot;]/td[@class=&quot;dialogMiddleCenter&quot;]/div[@class=&quot;dialogMiddleCenterInner dialogContent&quot;]/div[@class=&quot;targetPopup&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;c-bottom-margin&quot;]/div[1]/div[1]/input[@id=&quot;gwt-debug-&quot;]</value>
      <webElementGuid>5fc60a16-d60a-4170-9db1-2d16b11caea5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gwt-debug-']</value>
      <webElementGuid>76530280-d7f6-4514-a3ce-52aec1cd4696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>921d0170-c47b-47bf-878e-59140bebaa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'gwt-debug-']</value>
      <webElementGuid>ecf22c42-3982-499b-b4f7-a4ecd540b615</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
