<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Existing</name>
   <tag></tag>
   <elementGuidId>1cb860ee-208c-4d31-ad32-5fc47a0ec7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#existingpalette</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='existingpalette']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Existing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e444768-06ab-4628-827a-2d569b60a897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#existing</value>
      <webElementGuid>b79c000e-c9f3-4949-8648-0908e98f3b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>existingpalette</value>
      <webElementGuid>15f8e2ad-86cb-4697-b557-a3847e76d4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ef09cc7a-d4f0-4056-b38a-71f022ef8d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Existing</value>
      <webElementGuid>890350fc-e589-4b49-9871-daef7b23ac6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingpalette&quot;)</value>
      <webElementGuid>dd2d2b34-e469-4fb8-bf2a-f417688bd2b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='existingpalette']</value>
      <webElementGuid>e7397851-a762-4968-ad22-0a14ce8b9d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>835b69c4-42e7-4f03-a69d-141c0bc0b2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Existing')]</value>
      <webElementGuid>00eb2ffb-d46a-4584-819f-f324c7f86ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[2]/following::a[1]</value>
      <webElementGuid>a37e48f8-9d0b-4f98-9d67-afd9e0548433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/following::a[2]</value>
      <webElementGuid>2fc57cab-8e45-40fc-956a-68923c617209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::a[1]</value>
      <webElementGuid>3720086a-222f-4bf6-9e70-edaa71fb2097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help text goes here'])[1]/preceding::a[1]</value>
      <webElementGuid>9acc20ef-b8fe-40f9-9fe5-97419e5a0fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Existing']/parent::*</value>
      <webElementGuid>5c2fd13a-d5f5-4ec6-936c-0f37a87b5f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#existing')]</value>
      <webElementGuid>e499aa86-96f5-4ca9-bf14-9356d7828ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>c97bd6ad-db1b-42f1-a4f9-1bb18fa8ea41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#existing' and @id = 'existingpalette' and (text() = 'Existing' or . = 'Existing')]</value>
      <webElementGuid>3547d252-7ce7-41ab-951d-0cc2046fa6e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
