<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>d9f04df9-427d-496c-9ff8-b52dd0a0da90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.actionLinkArea > ul.breadcrumb.pipe-separated-links > li:nth-of-type(2) > a.c-inline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='propsarea']/div/div[2]/table/tbody/tr/td/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Save&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f5d1b35-ef8a-4752-a8cb-04eae7704c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inline</value>
      <webElementGuid>0e06538f-067f-4609-8993-c4a976faf991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ac06f94f-b08c-4043-88a7-afc74d241273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ab5c67f2-babc-46e7-8570-7c446aee01cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propsarea&quot;)/div[@class=&quot;cpmBottomPanelHeader&quot;]/div[@class=&quot;col-md-6 text-right&quot;]/table[@class=&quot;pull-right&quot;]/tbody[1]/tr[1]/td[@class=&quot;actionLinkArea&quot;]/ul[@class=&quot;breadcrumb pipe-separated-links&quot;]/li[2]/a[@class=&quot;c-inline&quot;]</value>
      <webElementGuid>98a7840c-552f-4792-ad1f-487a941b98d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propsarea']/div/div[2]/table/tbody/tr/td/ul/li[2]/a</value>
      <webElementGuid>8db09c4b-fcd5-4d34-90a1-858cf2c3d224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>fa7d21c2-1457-41b2-b675-c3301912cb89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add row'])[2]/following::a[1]</value>
      <webElementGuid>98425a0a-695d-493a-b7dc-0086ef071040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editing Product/Package: Product/Package -'])[1]/following::a[2]</value>
      <webElementGuid>9e2685af-070b-4316-b4e7-35f4c7c8fb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>8f588f24-bb43-4ab5-b139-fef7b39f0f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export to Excel'])[1]/preceding::a[2]</value>
      <webElementGuid>c590f528-8789-4671-9569-c1b4f7c38bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>1466c9a0-8b1f-4c56-8027-3684de936170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[2]/a</value>
      <webElementGuid>e8d8ad01-7eb4-4887-bd0f-b1803d527037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Save' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>69762320-93ad-438a-b732-dc5db9ca1c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
