<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Show Zero Charge On Invoice_dhxform_img chbx0</name>
   <tag></tag>
   <elementGuidId>9702bb7e-37f4-445c-bc0d-32af9628c2d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='recordView']/div[2]/div/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > div > div > .dhxform_base_nested > .dhxform_base > .dhxform_item_label_top > .dhxform_control > .dhxform_img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66dff3be-8a5e-4fe2-954c-5d960e822dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_img chbx0</value>
      <webElementGuid>eeb01331-a91a-4d26-88b7-067220359819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recordView&quot;)/div[@class=&quot;dhxform_base&quot;]/div[@class=&quot;block_dhxform_item_label_top c-form-field&quot;]/div[@class=&quot;dhxform_obj_dhx_skyblue dhxform_block&quot;]/div[@class=&quot;dhxform_base_nested in_block&quot;]/div[@class=&quot;dhxform_base&quot;]/div[@class=&quot;dhxform_item_label_top c-bold&quot;]/div[@class=&quot;dhxform_control dhxform_img_node&quot;]/div[@class=&quot;dhxform_img chbx0&quot;]</value>
      <webElementGuid>951f0bf3-3dce-4223-b0ee-854fd6640842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>d35fbe5d-a787-41ba-9f19-6b1b6fcbcb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>a22db3f8-308d-4364-9c0c-88c6d5460c5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
