<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dhxId_JCEel9d0KBoH</name>
   <tag></tag>
   <elementGuidId>cf36692e-76aa-4c29-bf15-77f8c3eb2a43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Currency']//following::div//input)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dhxId_JCEel9d0KBoH</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Currency*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd224de1-5a18-4d5f-aa86-06b53177c868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a258fd80-e653-49e5-bbfd-35a25dceb53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxcombo_input</value>
      <webElementGuid>97be35e9-9be0-48b3-8444-4728403878df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c5a5ba5-d130-466f-96cf-ef95cb79c228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_JCEel9d0KBoH</value>
      <webElementGuid>1b5a4aae-dc1b-4ed7-b954-cabb0d86a08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dba05945-9262-4634-998b-e5fa824fb0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please select</value>
      <webElementGuid>4a4dedce-5a72-45ff-b575-c83f6f068ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_JCEel9d0KBoH&quot;)</value>
      <webElementGuid>157dee76-c323-45b8-8da0-6df505b2dcb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_JCEel9d0KBoH']</value>
      <webElementGuid>3dc1858c-16e9-47cf-91b7-454395c757ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div/div/div/div/div[2]/div[2]/span/div/input</value>
      <webElementGuid>43603a0a-844a-48b0-b30e-808cf40e958b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>80e7f90f-491d-4bd0-aa60-2bf4ecf89220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dhxId_JCEel9d0KBoH' and @placeholder = 'Please select']</value>
      <webElementGuid>73544738-9718-40c0-8016-5305c93dfbd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
