<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Group Name</name>
   <tag></tag>
   <elementGuidId>b62eea4d-b70f-4794-952d-88211f657ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_C2leQyYPyorR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Group Name']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Group Name*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4da1531c-2ba3-475a-a4c7-0d2c4bef2752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>560ee398-3f4e-409b-b45d-3df32ef740cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Group Name</value>
      <webElementGuid>7878a680-6cfe-46ad-aadf-7d6d1ec51d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_C2leQyYPyorR</value>
      <webElementGuid>b630967d-8f45-4bc8-ba14-d3d655b5fc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>b20bea69-6ad0-46cd-bd53-783af6df6ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>04a7cbc5-3210-4ebe-b97d-5e8306fd3daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>6427d1e6-4a72-44c4-a130-eeae3d733518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_C2leQyYPyorR&quot;)</value>
      <webElementGuid>f833e07d-a21b-4a5b-9968-46ff81931d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_C2leQyYPyorR']</value>
      <webElementGuid>0e038460-4cb5-4fd1-a885-f0bd9ae50d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>86d266ef-0d96-4ccb-a7ce-531d7c23a895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>8d26061a-b4fc-46a0-a2fb-8916846c94f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Group Name' and @id = 'dhxId_C2leQyYPyorR' and @type = 'TEXT']</value>
      <webElementGuid>deb55d65-df07-4210-8cde-8fc3eafefffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
