<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Tariff Charge</name>
   <tag></tag>
   <elementGuidId>e0300424-a07f-4ca4-9a6b-9c61d3887aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_0HJFC3efEBqe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dhxId_0HJFC3efEBqe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tariff Charge*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0386f95c-0c60-430e-a77d-5d8af0a31edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>4463ce11-cac6-49e5-9974-8e53184b773a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Tariff Charge</value>
      <webElementGuid>d9dce007-bbbb-41dc-8d5a-3a0ba280cbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_0HJFC3efEBqe</value>
      <webElementGuid>a3b17120-e9c7-44e3-abb5-0acd93ae4f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>e1490da2-c169-4c4e-af41-c1ad304c6da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9aab582d-d953-49eb-ba31-be0ae8dbf14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_0HJFC3efEBqe&quot;)</value>
      <webElementGuid>9fa0ca42-2d36-469e-a008-9d406fde4a08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_0HJFC3efEBqe']</value>
      <webElementGuid>737c2070-d634-4861-af6e-40cca5c40a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div[7]/div/div/div/div/div[2]/input</value>
      <webElementGuid>6680ab9d-aadf-43f1-832b-0b19cc86dae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]/div/div/div/div/div[2]/input</value>
      <webElementGuid>2ed93a28-fe42-4fc4-b8dd-6a05262ffe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Tariff Charge' and @id = 'dhxId_0HJFC3efEBqe' and @type = 'TEXT']</value>
      <webElementGuid>94ca4c70-f7ad-45a7-b8b2-eebb79ed3e7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
