<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Maximum Products</name>
   <tag></tag>
   <elementGuidId>7e550a9c-e6e8-4ed8-ad24-949b7d594262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_FhnWLthftd6C</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Maximum Products']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Maximum Products*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91edd308-17c5-4b3c-959c-525f31dfe7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>44920225-472f-4036-8ec7-3be69c1bbfa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Maximum Products</value>
      <webElementGuid>21f4fcaf-f3cf-47b5-a1b9-cd78fc0f14a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_FhnWLthftd6C</value>
      <webElementGuid>242d9d71-bf3a-479f-a7c7-c638f0a2ad09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>726a3223-b8b3-4f4d-936e-9c5740fe0db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c8eaaacf-95b4-46b9-9f90-ccbc129effc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_FhnWLthftd6C&quot;)</value>
      <webElementGuid>39bc5a06-c2d5-4a7d-a808-02df8d8b1704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_FhnWLthftd6C']</value>
      <webElementGuid>f2cd0d0b-45e9-4121-a209-6d5e2dc4c12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[3]/div/div/div/div/div[2]/input</value>
      <webElementGuid>d435ed83-c75f-4d83-a50e-47948027bd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/input</value>
      <webElementGuid>70ba9a40-5ca8-4370-a599-0d8cb663d13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Maximum Products' and @id = 'dhxId_FhnWLthftd6C' and @type = 'TEXT']</value>
      <webElementGuid>028565e8-735f-4e9b-96ca-110582d006ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
