<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Gl 11 Cost</name>
   <tag></tag>
   <elementGuidId>825c2699-fd5d-4158-b616-973500eee74d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_BxcPwu5k4EPe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dhxId_BxcPwu5k4EPe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gl 11 Cost*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f57e8de-fc78-42fb-9a77-e5f69197aece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>fd214449-0b85-4d73-b8e5-2ad549877a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gl 11 Cost</value>
      <webElementGuid>4e006747-791f-4640-b418-748e04a99722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_BxcPwu5k4EPe</value>
      <webElementGuid>78badec8-2804-411a-9356-864db353a73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>b3089d77-15a7-4b4f-aab0-de92b582cd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>df3dd5fd-8d68-4408-946b-ba509e15a96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>4fd5ae71-8ba4-49f5-9f38-eccedfb0e26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_BxcPwu5k4EPe&quot;)</value>
      <webElementGuid>510528df-17d0-4e43-be6f-223a39a39770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_BxcPwu5k4EPe']</value>
      <webElementGuid>f2f168a4-a0ab-4434-aac5-0ddb1cd89efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>b595f2f0-97b3-4386-b9bc-b5a85006e765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>e29364ec-4d52-4a7e-ad3c-8fad6b43e4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Cost' and @id = 'dhxId_BxcPwu5k4EPe' and @type = 'TEXT']</value>
      <webElementGuid>bf7d8a2d-eb5f-4a4f-9d85-4f241e836488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_4l5wrLPwUv3V']</value>
      <webElementGuid>adb49257-b68a-40af-bdaa-35ae6ca05bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Cost' and @id = 'dhxId_4l5wrLPwUv3V' and @type = 'TEXT']</value>
      <webElementGuid>a59adea1-37be-4527-b064-204cf460985c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
