<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Order 11_1</name>
   <tag></tag>
   <elementGuidId>07b82890-729b-466c-a8a8-60a8fa8c7f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_5YOdq3Jp1uX0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dhxId_5YOdq3Jp1uX0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Order 11*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df5d402b-5080-41b6-9927-be150138c1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>f425e508-2ab1-4566-afdc-4f1cce7e29a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Order 11</value>
      <webElementGuid>d6499179-a332-4b94-9f4c-d4e7cb4f4683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_5YOdq3Jp1uX0</value>
      <webElementGuid>ba7a65e6-2cdd-47ec-b15e-9138c7b70e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>0c2f56b0-d04d-4a26-a6da-6f437937aff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f74e7dbb-0686-4473-a4f7-dea922caa4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>d6771c48-53a1-44c7-87e4-af798cc17a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_5YOdq3Jp1uX0&quot;)</value>
      <webElementGuid>94699eb8-56d1-4ac2-afd2-e95a1c0886f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_5YOdq3Jp1uX0']</value>
      <webElementGuid>16022567-bb58-468c-aa42-938738474c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>eb0bb13d-ed5a-4d8a-8b47-1ec7e5ca644d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>179cfa72-e5d2-46cb-8151-ff9448c0e8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Order 11' and @id = 'dhxId_5YOdq3Jp1uX0' and @type = 'TEXT']</value>
      <webElementGuid>642008d6-bf04-4115-8882-722f475a5dfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
