<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Gl 11 Income</name>
   <tag></tag>
   <elementGuidId>e3452883-dc27-49d8-ae68-9ac919e8d8b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_FUqBlqdrHziL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dhxId_FUqBlqdrHziL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gl 11 Income*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28b951ec-69e5-4b92-b68d-d99674267bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>b33cc8f4-c6d8-4a92-8352-eb25642ef7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gl 11 Income</value>
      <webElementGuid>6e098b57-e67b-4b3a-a3f8-feb0c0cce079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_FUqBlqdrHziL</value>
      <webElementGuid>1a21f54f-cfae-4020-83d7-d9f27ff7ea7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>826ec44c-dee5-4a9b-bfe6-804022971332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>c223c941-9d1e-476b-8060-fc007860c0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>23dfa59a-608d-40f8-89de-decc15ddef64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_FUqBlqdrHziL&quot;)</value>
      <webElementGuid>c7d200b0-889f-4f9a-b02b-6dc7e83bc024</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_FUqBlqdrHziL']</value>
      <webElementGuid>46bc3f6a-b271-44b9-87e9-23f653a7f5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>7adcdb03-f679-489e-8476-4143ecf35b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>a470fb4f-25ec-41c4-8a76-2e1f84b3859f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Income' and @id = 'dhxId_FUqBlqdrHziL' and @type = 'TEXT']</value>
      <webElementGuid>1beea9f7-7739-4cdf-ad1d-055abd6b5632</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
