<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Minimum Products</name>
   <tag></tag>
   <elementGuidId>44592dc6-f0b7-4ce1-a3ff-8c3e68e477b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_D6kcFigZIJns</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Minimum Products']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Minimum Products*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cc216e3-db4b-4b81-99e2-81c46c3b1128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>3e44a3e2-3000-41aa-9e95-0b3d199bf3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Minimum Products</value>
      <webElementGuid>27ca2efd-d148-468f-a6d9-1b6758ec0783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_D6kcFigZIJns</value>
      <webElementGuid>d70f41c1-6c50-4b47-8143-38a22bad445a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>d7e9c14f-bd68-4000-a55a-5d181bcb4e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e8d0f41d-ded6-4467-bae4-0360d3013da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_D6kcFigZIJns&quot;)</value>
      <webElementGuid>8e2024c7-3fc5-4b84-9e68-91e37a10198c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_D6kcFigZIJns']</value>
      <webElementGuid>1a5ff480-fab7-4d25-9a5f-903a228adc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>cf4e4b35-2c73-4c90-9c71-74be46aacaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>f08fb907-1cec-48cc-88b8-daa91e79b887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Minimum Products' and @id = 'dhxId_D6kcFigZIJns' and @type = 'TEXT']</value>
      <webElementGuid>5b29a8d9-5f1f-4cf6-97ee-84cf668c8f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
