<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__dhxcombo_select_img</name>
   <tag></tag>
   <elementGuidId>6e09d84a-b01f-4b44-ac3a-e0fccd26c5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dhxform_item_label_top.validate_error > div.dhxform_control > span > div.dhxcombo_dhx_skyblue > div.dhxcombo_select_button > div.dhxcombo_select_img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='recordView']/div/div[6]/div/div/div/div/div[2]/span/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(6) > div > .dhxform_base_nested > .dhxform_base > .dhxform_item_label_top > .dhxform_control > span > .dhxcombo_dhx_skyblue > .dhxcombo_select_button > .dhxcombo_select_img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af870212-300d-45ba-835e-35b29cc283e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxcombo_select_img</value>
      <webElementGuid>b0b091d6-2fe0-45cc-bd4f-ef6433bb6d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recordView&quot;)/div[@class=&quot;dhxform_base&quot;]/div[@class=&quot;block_dhxform_item_label_top c-form-field&quot;]/div[@class=&quot;dhxform_obj_dhx_skyblue dhxform_block&quot;]/div[@class=&quot;dhxform_base_nested in_block&quot;]/div[@class=&quot;dhxform_base&quot;]/div[@class=&quot;dhxform_item_label_top validate_error&quot;]/div[@class=&quot;dhxform_control&quot;]/span[1]/div[@class=&quot;dhxcombo_dhx_skyblue&quot;]/div[@class=&quot;dhxcombo_select_button&quot;]/div[@class=&quot;dhxcombo_select_img&quot;]</value>
      <webElementGuid>8dc137b2-dbf5-4891-bd1a-be0189c0e118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[6]/div/div/div/div/div[2]/span/div/div/div</value>
      <webElementGuid>6ece9e6a-b293-4875-ae60-afd21005619f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/span/div/div/div</value>
      <webElementGuid>170236ce-9148-43b4-a296-c8d2311543bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div/div/div/div/div/div[2]/span/div/div/div</value>
      <webElementGuid>ab223039-d5e0-451a-a396-432fe0c184aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/span/div/div/div</value>
      <webElementGuid>a768d77d-051c-4122-b864-6beafe1d3eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
