<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Tariff Charge</name>
   <tag></tag>
   <elementGuidId>2bf76cb3-6959-40b6-8f1e-30f014d9aaa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'Tariff Charge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dhxId_AzZ58dlwfKDK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tariff Charge*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb228fcd-cff2-489a-a832-eb9c957d58b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>6bdb33fa-c4cd-4c05-8276-905d38157408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Tariff Charge</value>
      <webElementGuid>556bd709-51bd-4ebb-b292-f8a6fa04381f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_AzZ58dlwfKDK</value>
      <webElementGuid>95cf2449-ebf0-4a83-b74b-3a2fc27090a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>c4b170d7-c43b-4817-9b46-95d327a517de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>71661d38-fadc-43d7-87dd-578ccd500069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_AzZ58dlwfKDK&quot;)</value>
      <webElementGuid>d3faf4fa-26a6-44b9-92f0-6a0e3f8e181f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_AzZ58dlwfKDK']</value>
      <webElementGuid>8cb12ac0-aa6b-45f2-be6d-03bc9d28435b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div[7]/div/div/div/div/div[2]/input</value>
      <webElementGuid>b79ec90f-c58a-4a90-85f6-e938f8ea0d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]/div/div/div/div/div[2]/input</value>
      <webElementGuid>3981e52d-bcef-456c-9712-863b1401acad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Tariff Charge' and @id = 'dhxId_AzZ58dlwfKDK' and @type = 'TEXT']</value>
      <webElementGuid>b66a97ba-0dde-419a-bc69-e3ccee3eb0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_eA6jeuTA6kr4']</value>
      <webElementGuid>c4110a5f-f515-42ef-9064-46bdefec4c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Tariff Charge' and @id = 'dhxId_eA6jeuTA6kr4' and @type = 'TEXT']</value>
      <webElementGuid>71ab55b3-51fe-4339-a490-b1e111043204</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
