<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Product Description</name>
   <tag></tag>
   <elementGuidId>631a04b2-8ce7-4603-a363-92f252450b3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_FkCoWsNOVhKm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Product Description']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product Description*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49dd3b06-d790-4174-9017-241405ac3fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>b33c1b57-2399-4d3b-8d3a-dd09473b09fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Product Description</value>
      <webElementGuid>854a83be-a720-40c8-a18f-378640e6c2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_FkCoWsNOVhKm</value>
      <webElementGuid>0d437bf1-d713-4048-b232-bf964623a399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>25c4a1ce-9f72-4e72-9cbf-fabd25bc1b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>de81afc6-9669-44c6-bdbf-1e5d8f3d2b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>89792d5d-6a88-484b-98c9-98d4c448f406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_FkCoWsNOVhKm&quot;)</value>
      <webElementGuid>5bf9a09a-9257-4277-a8a0-4f1db6d2a578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_FkCoWsNOVhKm']</value>
      <webElementGuid>24229eb5-1c25-492b-9b05-1c2f61464e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[4]/div/div/div/div/div[2]/input</value>
      <webElementGuid>a6c4431d-85e4-4b52-b8fd-70198ba32a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>715cd5c2-8829-4169-99ff-761912e6c1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_FkCoWsNOVhKm' and @type = 'TEXT']</value>
      <webElementGuid>c38cb1f3-8fab-44f3-b570-55e0749831f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_nIPNNPgu0iA9']</value>
      <webElementGuid>c39f63ce-2f22-4dbb-8f68-15effab8560f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_nIPNNPgu0iA9' and @type = 'TEXT']</value>
      <webElementGuid>f861a3e9-fb9a-46e5-9ff8-e05c6c38afb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
