<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Gl 11 Income</name>
   <tag></tag>
   <elementGuidId>c5eda785-fdfe-448f-acc1-514b75ea9fc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'Gl 11 Income']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dhxId_J1jZ2IQy1Tvx</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gl 11 Income*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9bab874-aa67-44f8-bf1b-f0207d6e018a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>7d9a78f8-50ee-4794-8820-33f3163cb444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gl 11 Income</value>
      <webElementGuid>772ef63e-39ea-43d2-9747-43bd57153072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_J1jZ2IQy1Tvx</value>
      <webElementGuid>2a6f0a31-6046-48e6-b177-f7b82e265d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>ca6b3bdf-e370-4de0-af28-a150f216b37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>667ebd36-c69f-48c4-8f62-fda6f3bb3829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>6c440eec-bd77-4a93-a0b6-00db647acd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_J1jZ2IQy1Tvx&quot;)</value>
      <webElementGuid>fa9f166e-06c7-4cad-a7d6-3898efd24deb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_J1jZ2IQy1Tvx']</value>
      <webElementGuid>224b9906-4327-4c99-ae73-6d739eed068c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>d470e68b-cbaa-4972-bd9a-5976ce058548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>1086aef4-7026-4ce2-8ced-149666bd2d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Income' and @id = 'dhxId_J1jZ2IQy1Tvx' and @type = 'TEXT']</value>
      <webElementGuid>1b6a3332-2eef-4958-9715-534dd2fdec92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_rKzPLMPjHA4d']</value>
      <webElementGuid>1e95978e-e93c-4907-8779-650802c42c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Income' and @id = 'dhxId_rKzPLMPjHA4d' and @type = 'TEXT']</value>
      <webElementGuid>b5a9ad14-7260-4784-a85c-3172c2f9ee1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
