<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dhxId_kYWw6T9lBpIe</name>
   <tag></tag>
   <elementGuidId>ab4eed64-4e33-4281-8e52-7c4d98c42c14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Product Charge Type']//following::div//input)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dhxId_kYWw6T9lBpIe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product Charge Type*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc41f4f5-6a2c-4cc8-8d50-d31d8aee6bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>afa9712a-f8e4-4c78-bff3-a552c309c49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxcombo_input</value>
      <webElementGuid>1a95c91f-a7cb-42d3-a3eb-e302bdb18ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a247d491-391a-4b3f-a7be-c7a0a983a730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_kYWw6T9lBpIe</value>
      <webElementGuid>0c584530-8b25-44c2-a186-62db9a3cb8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>f12ecd52-f4ee-4ed6-b27f-296965cd4e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please select</value>
      <webElementGuid>1b02697d-8f07-4583-89d3-7e12dc0c4fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_kYWw6T9lBpIe&quot;)</value>
      <webElementGuid>eeb99780-469e-4829-8787-0cf32a20477c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_kYWw6T9lBpIe']</value>
      <webElementGuid>0e12f37c-468b-4cfa-97f6-cbe81b747557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[6]/div/div/div/div/div[2]/span/div/input</value>
      <webElementGuid>e68fa501-f91c-4a89-9c0d-1fc03ac6d450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/span/div/input</value>
      <webElementGuid>34bb5c01-0b0b-44ef-a3b8-f69fc7af4e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dhxId_kYWw6T9lBpIe' and @placeholder = 'Please select']</value>
      <webElementGuid>c37d02f1-5d1c-415b-ac52-0e9b7beb9cff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
