<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Version 1</name>
   <tag></tag>
   <elementGuidId>c5d66a67-7c13-4f11-a528-01b5f8c1cd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.hyperlink > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;window.openInCatalogueSelection('28','1')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Version 1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b62f3f7-285a-4000-b5aa-4a0f6483ba2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.openInCatalogueSelection('28','1')</value>
      <webElementGuid>5adf9670-18b1-4545-847c-3c610d6f1ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Version 1</value>
      <webElementGuid>fc261715-b143-47a0-98a9-0222a1a00fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightarea&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;panel panel-default c-dashboard-tab&quot;]/div[@class=&quot;panel-body version-target-panel auto-height bottom-margin-50 dashboard-tab-content&quot;]/div[@class=&quot;tab-pane fade in active&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[@class=&quot;hyperlink&quot;]/a[1]</value>
      <webElementGuid>b776d1a1-2a4f-46ad-acbf-ee3b60b09967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;window.openInCatalogueSelection('28','1')&quot;]</value>
      <webElementGuid>f8ead02a-c2aa-4257-85cb-e630365f4e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightarea']/div/div[3]/div/div/div/div/div[2]/div/table/tbody/tr/td/a</value>
      <webElementGuid>84ad49c5-82c9-4735-a49a-31ab50b5e233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Version 1')]</value>
      <webElementGuid>7d683bc2-08d6-4695-bc5e-26763e354278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>5ff6bdef-06ef-47de-a73d-d697aaf87921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited'])[1]/following::a[1]</value>
      <webElementGuid>912249ef-9aa7-42f8-b5ee-1fc6dc895485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Revert)'])[1]/preceding::a[1]</value>
      <webElementGuid>f9229541-cb3b-4ee6-af3e-6dd4bffbba14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Version 1']/parent::*</value>
      <webElementGuid>c0b6a882-cfcd-47ad-8c21-7f29db85d5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>5f0cd7b9-2570-4147-83d6-8b77765aff9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Version 1' or . = 'Version 1')]</value>
      <webElementGuid>b5f731a2-b684-475a-bb77-59e1add98659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
