<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gibtelecom - Pooja_DemoEdited 1251 (Me 1250)</name>
   <tag></tag>
   <elementGuidId>77f15454-a5b7-4d37-b3e0-052fd3ffc09e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.projects-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Gibtelecom - Pooja_DemoEdited: 12:51 \(Me: 12:50\)$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a1cf1ae-5e6e-437b-bd3a-25a29df18ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>projects-list</value>
      <webElementGuid>5233322d-5569-410d-a6a4-7696f28fc4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gibtelecom - Pooja_DemoEdited: 12:51 (Me: 12:50)</value>
      <webElementGuid>7b573247-ce52-43b0-8220-b07d2a44784f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftarea&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body c-panel-reduce-padding&quot;]/div[@class=&quot;projects-list-outer auto-height bottom-margin-20&quot;]/div[@class=&quot;projects-list-inner&quot;]/div[@class=&quot;projects-list&quot;]</value>
      <webElementGuid>4ab6d56d-e374-4e73-88dc-367c6884d295</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>3981f40e-321b-46d5-b39a-2d81089b82fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects Available'])[1]/following::div[4]</value>
      <webElementGuid>e1990ae4-bfc7-43c7-8097-c5057b76bef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>1cbacf0c-43ae-4a90-b0e4-4af85d36e7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gibtelecom - Pooja_DemoEdited: 12:51 (Me: 12:50)' or . = 'Gibtelecom - Pooja_DemoEdited: 12:51 (Me: 12:50)')]</value>
      <webElementGuid>d4c667e8-beb3-4641-820f-78e409fb279e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
