<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Existing</name>
   <tag></tag>
   <elementGuidId>711cda4c-6cd2-44cf-8559-4ab598f69bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='existingpalette']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#existingpalette</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#existing' and @id = 'existingpalette' and (text() = 'Existing' or . = 'Existing')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Existing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38891b17-59fb-4ff2-9efa-1f6b98d104d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#existing</value>
      <webElementGuid>becad633-68ae-4612-8d49-a8b28456f433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>existingpalette</value>
      <webElementGuid>e14330f9-41f1-45d8-bf9f-6e1ee62ca4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>74212c50-7b03-417a-a608-acdd20f700e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Existing</value>
      <webElementGuid>faadbe13-74a3-4d79-a04f-36b0fc33aac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingpalette&quot;)</value>
      <webElementGuid>b1e38341-9974-4c8b-a7c4-d1675720720a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='existingpalette']</value>
      <webElementGuid>0aae5234-88cf-48bc-bd84-210acc51802d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>f286acfb-1fa0-48c4-b781-b810f6629bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Existing')]</value>
      <webElementGuid>0927b0a8-05ae-4c7b-ade9-08d14c659a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[2]/following::a[1]</value>
      <webElementGuid>d1030858-c0da-48d4-93d0-3bdff475e7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/following::a[2]</value>
      <webElementGuid>eb23b226-af78-4159-8562-3e1876eb07da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::a[1]</value>
      <webElementGuid>c1529106-c6ad-4c0d-94b7-46aeaf18ad1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help text goes here'])[1]/preceding::a[1]</value>
      <webElementGuid>661462ba-9875-402f-8b81-19a6430216ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Existing']/parent::*</value>
      <webElementGuid>7df315e2-6da6-454a-9e74-b57a0f3bca37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#existing')]</value>
      <webElementGuid>3d1ac3e9-a8e9-497d-b530-fd2b9020816c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>b7dfa224-64c0-48bb-a5e0-8cd5be81765f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#existing' and @id = 'existingpalette' and (text() = 'Existing' or . = 'Existing')]</value>
      <webElementGuid>d6533d32-eced-4e81-a39c-170f332b99ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
