<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>ca7c83e2-7b5c-435a-91d8-7f8e2e49be71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='propsarea']/div/div[2]/table/tbody/tr/td/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.actionLinkArea > ul.breadcrumb.pipe-separated-links > li:nth-of-type(2) > a.c-inline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Save&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6e6c489-7225-4b4b-a410-159ea34e746f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inline</value>
      <webElementGuid>c65e2358-5184-4206-99e0-c065bb51b879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>edd49c7d-6a4a-4a05-9936-b76f00131925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>7d5b941a-f635-4ad0-a490-4879cd5f571f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propsarea&quot;)/div[@class=&quot;cpmBottomPanelHeader&quot;]/div[@class=&quot;col-md-6 text-right&quot;]/table[@class=&quot;pull-right&quot;]/tbody[1]/tr[1]/td[@class=&quot;actionLinkArea&quot;]/ul[@class=&quot;breadcrumb pipe-separated-links&quot;]/li[2]/a[@class=&quot;c-inline&quot;]</value>
      <webElementGuid>02d5f411-7f0e-4868-a28b-907a4df12846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propsarea']/div/div[2]/table/tbody/tr/td/ul/li[2]/a</value>
      <webElementGuid>14f2ef8d-7f10-4b5b-a9f1-9eed0efc02d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>1035f1d4-1a9a-4c96-84a5-dbfbbfb523de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add row'])[2]/following::a[1]</value>
      <webElementGuid>96910b59-368c-4150-ae30-a95827501a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editing Network Service: ALP_TO_ANY'])[1]/following::a[2]</value>
      <webElementGuid>40dd8894-36f4-4d96-97ea-eca471af5a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>59595291-8bdb-4871-b0ba-8490f3149630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export to Excel'])[1]/preceding::a[2]</value>
      <webElementGuid>8c1774b4-70cc-463a-a6cf-0167831c6473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>5ddcf6b6-08cc-4ac6-8479-138172984217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[2]/a</value>
      <webElementGuid>584f9e2e-3bdc-4e08-af1d-7fed3c897224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Save' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>b80d9548-2f02-470e-928d-fac1b04cebee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
