<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an optionLINK - Link_Prod_Project</name>
   <tag></tag>
   <elementGuidId>4c0f1b5e-f2d4-4a2e-82b7-b17a86ed0e42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gwt-debug-project']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-project</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-project</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c11a1adc-db7f-4e18-af38-c3736347e122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-mandatory c-simple-ddl c-simple-ddl-width</value>
      <webElementGuid>f14566c9-38f2-4550-88f1-3aa7fb587b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-project</value>
      <webElementGuid>0da44017-c6dd-428f-91e3-89c1dad2bde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an optionLINK - Link_Prod_Project</value>
      <webElementGuid>76731a4f-006a-479f-8c87-d4a99e0ebfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-project&quot;)</value>
      <webElementGuid>a619cd0d-5229-49ae-9d8e-b17719b61ea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gwt-debug-project']</value>
      <webElementGuid>7b2d0fa2-a05c-4681-9b99-95624d2abe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>8b4be683-743d-489c-8787-7026c5608a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[1]/following::select[1]</value>
      <webElementGuid>22cfb96f-d003-427b-9fe5-6dd7bc3e5ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Details'])[1]/following::select[1]</value>
      <webElementGuid>95748abf-3ae6-4e84-98fb-851165bf7382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[1]/preceding::select[1]</value>
      <webElementGuid>1f343a7c-50f9-42c4-bb6c-61d589844dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target'])[1]/preceding::select[2]</value>
      <webElementGuid>11c19da6-d5ce-460f-9674-64c8e5ef341b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1ab596f8-1371-4c85-8294-38263e6004a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gwt-debug-project' and (text() = 'Select an optionLINK - Link_Prod_Project' or . = 'Select an optionLINK - Link_Prod_Project')]</value>
      <webElementGuid>244aa30a-f7a6-4fa7-9afb-a47389750edb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
