<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an optionLINKCNF1 CCSLINKCNF1 CRM</name>
   <tag></tag>
   <elementGuidId>5393221f-516e-4894-a04a-f9f6bb27cd5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gwt-debug-target']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-target</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-target</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>95b02d22-4056-4a19-9bab-23c3a55b18e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-mandatory c-simple-ddl c-simple-ddl-width</value>
      <webElementGuid>21cd789a-a4af-437b-878e-ef779700be4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-target</value>
      <webElementGuid>b23ff64f-18a9-44dc-ade2-5543671b1841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an optionLINKCNF1 CCSLINKCNF1 CRM</value>
      <webElementGuid>52682b2b-8cb9-4830-9df8-f31e69a57115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-target&quot;)</value>
      <webElementGuid>abc620d3-4e06-4ef1-a1eb-6f43ec01bc31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gwt-debug-target']</value>
      <webElementGuid>80c59552-6f25-4edb-863d-907f6c79d2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>c8bd042d-8027-43d8-913b-730e65ee3e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target'])[1]/following::select[1]</value>
      <webElementGuid>44139b29-c765-4ee0-9dac-0fd64882fd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[1]/following::select[2]</value>
      <webElementGuid>9d6e8412-3b9b-4625-bced-e908f9e25d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Type'])[1]/preceding::select[1]</value>
      <webElementGuid>87429bf5-7623-409c-865b-fdeddcf0ab40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish'])[4]/preceding::select[2]</value>
      <webElementGuid>eb0b8054-a459-4c6c-a7f3-17d2e1e25816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>a839a336-747b-4caa-acee-a3b0470ee37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gwt-debug-target' and (text() = 'Select an optionLINKCNF1 CCSLINKCNF1 CRM' or . = 'Select an optionLINKCNF1 CCSLINKCNF1 CRM')]</value>
      <webElementGuid>3f6fb0ab-a2c8-45cd-bcbb-7541f548e1a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
