<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_IOPROD_Project</name>
   <tag></tag>
   <elementGuidId>52538a3a-bbaa-4f13-ba9b-7cf7a60e9ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a.c-inline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toparea']/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;IOPROD_Project&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6efd3f13-5cfd-4532-ae62-7b1f2020e83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inline</value>
      <webElementGuid>d69c3310-1a51-4456-bbfe-cc489aba1afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>IOPROD_Project</value>
      <webElementGuid>c1931020-3b1e-4a97-8932-6353ea51e717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IOPROD_Project</value>
      <webElementGuid>79684d87-af74-4b65-8db5-1cbbf418ba8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toparea&quot;)/div[@class=&quot;indentPageInfo cpmTopPanelHeader_1&quot;]/div[1]/ul[@class=&quot;breadcrumb&quot;]/li[3]/a[@class=&quot;c-inline&quot;]</value>
      <webElementGuid>13f0e037-b1ea-4574-af0c-b7692062a367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toparea']/div/div/ul/li[3]/a</value>
      <webElementGuid>abcf918c-8924-4047-90a7-1119e5b523c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'IOPROD_Project')]</value>
      <webElementGuid>348f84e1-fe50-4870-9b4c-4bb9523610fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IO'])[1]/following::a[1]</value>
      <webElementGuid>07ec0e9d-21e4-4b3e-8eab-6cf0245456a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>af59bea9-e95f-4f36-ab57-386e6697e854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test - Version 1(work in progress)'])[1]/preceding::a[1]</value>
      <webElementGuid>755ca505-666a-4610-9b02-fbdc2fd17305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate'])[2]/preceding::a[2]</value>
      <webElementGuid>45d84d89-752e-40ce-b7c8-a5e1e274fa00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IOPROD_Project']/parent::*</value>
      <webElementGuid>d5e77b83-e25b-48a7-ad41-d0a42d66318e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>c1288b5e-b0d6-4d90-870c-b07c7c5b91d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'IOPROD_Project' and (text() = 'IOPROD_Project' or . = 'IOPROD_Project')]</value>
      <webElementGuid>95ee8dd3-c997-4ef0-ac18-dde61612b423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
