<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Validation is performed against the tar_5ee452</name>
   <tag></tag>
   <elementGuidId>a710e4da-2d27-4185-a735-86e50d1a773e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageBody']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.c-floaty-banner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pageBody div >> internal:has-text=&quot;Validation is performed against the targets defined. There is no CCS target, the&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1b10a62-cbad-4802-ad9e-adbc23d9dd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-floaty-banner</value>
      <webElementGuid>058c66d8-7a70-4cfd-8cc2-352b76c44a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gwt-comp-name</name>
      <type>Main</type>
      <value>com.cerillion.cpm.ui.components.bootstrap.BootBanners</value>
      <webElementGuid>5a6b54c1-75ef-4cc9-9413-584c723ca11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Validation is performed against the targets defined. There is no CCS target, therefore validation will exclude CCS entities.  ×  </value>
      <webElementGuid>26a77a16-ebcc-4ec1-abed-56c6d6d4b7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageBody&quot;)/div[@class=&quot;c-floaty-banner&quot;]</value>
      <webElementGuid>653c028d-b5c5-483b-89da-c53ec891b081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div</value>
      <webElementGuid>46392c67-95c8-4946-a614-a57e28493296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build: 1835'])[1]/following::div[2]</value>
      <webElementGuid>53f5d624-2889-4733-a17a-63970b20d002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='null null'])[1]/following::div[4]</value>
      <webElementGuid>b965651b-4917-4f12-b533-fa2e798410c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate'])[1]/preceding::div[6]</value>
      <webElementGuid>a73d91d1-d90f-46e6-82c3-d695f0f3fcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[6]</value>
      <webElementGuid>ca22c80f-db54-4895-a12a-3a454c77b6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>b65a85d2-d06b-4d9e-8fbf-6cdf01341a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Validation is performed against the targets defined. There is no CCS target, therefore validation will exclude CCS entities.  ×  ' or . = ' Validation is performed against the targets defined. There is no CCS target, therefore validation will exclude CCS entities.  ×  ')]</value>
      <webElementGuid>13af7275-c2d3-4fb6-97ec-c43f47ab130b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
