<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_IO</name>
   <tag></tag>
   <elementGuidId>c15df2f6-d415-4b15-835b-896c9a6cadcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > div.c-inline > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightarea']/div/div/div/ul/li[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;IO&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9263db0-e3e4-4295-a555-255cc3f7b353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IO</value>
      <webElementGuid>a5e6f89f-e974-4eb7-8530-bba9c182ef48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightarea&quot;)/div[1]/div[@class=&quot;row cpmTopPanelHeader_1&quot;]/div[@class=&quot;col-lg-8 pull-left&quot;]/ul[@class=&quot;breadcrumb&quot;]/li[2]/div[@class=&quot;c-inline&quot;]/a[1]</value>
      <webElementGuid>e701bf62-f8b9-4055-b1ff-8e4d2c7c4160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightarea']/div/div/div/ul/li[2]/div/a</value>
      <webElementGuid>34ddcce9-f3de-40eb-8788-aac794906d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'IO')]</value>
      <webElementGuid>1fc85116-ee3a-41ca-9369-764d1680a9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>8af46f07-7ae4-4c4a-8219-3da72da5b9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IO - Test'])[1]/following::a[2]</value>
      <webElementGuid>c64e4953-e7ce-4887-918b-5b3533cff46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IOPROD_Project'])[1]/preceding::a[1]</value>
      <webElementGuid>204bcfe6-d330-4335-a1bf-d414a21c0b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test - Version 1(work in progress)'])[1]/preceding::a[2]</value>
      <webElementGuid>caf29eaf-2c7b-4eec-a525-59c460475e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IO']/parent::*</value>
      <webElementGuid>2169e6d3-f006-4a3e-8783-b4102ce053e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>11103b42-8060-4c81-b6d3-3343aa62be17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'IO' or . = 'IO')]</value>
      <webElementGuid>d56e4ea8-8a39-4f4c-8518-2f16d1c61586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
