<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_login</name>
   <tag></tag>
   <elementGuidId>06192237-f0a7-4e2c-9d92-2e1c2efb749d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kc-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kc-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Sign In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91e00d08-04ec-4dac-8525-8f9fe093331e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>48ff07fe-974d-4038-8312-0b4b66c346bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-login-button btn btn-primary btn-lg</value>
      <webElementGuid>137bf3ab-9ec0-43fa-9c70-2b3af8bc78b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>219a3604-c45e-4c6c-a60b-c31ee623f483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kc-login</value>
      <webElementGuid>261b6a71-3183-4978-8d6e-caef10b07152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bda9d53d-f911-42ed-a452-7dfc5cb31f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>c0fcf479-afd2-4118-affc-8c1c04e3e733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-login&quot;)</value>
      <webElementGuid>b946022a-47fc-47ef-a92e-dac3f99c2b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kc-login']</value>
      <webElementGuid>a1cf959e-9dc6-4d52-aa6d-bbaa6e676358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-form-buttons']/input</value>
      <webElementGuid>d4dd5e0b-d090-4959-b1ac-c665833e3977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>15958464-6bea-400c-bb13-1b736a124a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login' and @id = 'kc-login' and @type = 'submit']</value>
      <webElementGuid>bee40fc4-10f9-4b97-be86-5d384f147196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
