<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an optionIO - TestProjectIO -_52147f</name>
   <tag></tag>
   <elementGuidId>748a5f3d-b3ae-4a09-93a4-3edbafa8e614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gwt-debug-project']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-project</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-project</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>30142ad5-481c-4c76-ab02-15dec190d608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-mandatory c-simple-ddl c-simple-ddl-width</value>
      <webElementGuid>2a0dd2a8-bd45-40e1-b646-3270066ca5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-project</value>
      <webElementGuid>79e2dc75-8b47-495d-b763-65cb3283fd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an optionIO - TestProjectIO - TestProjectIO - ToluTest ProjectIO - IOPROD_ProjectIO - IOProject</value>
      <webElementGuid>28e7f903-8d2d-4f09-9a28-eb678aa59568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-project&quot;)</value>
      <webElementGuid>5affdddd-5d79-441c-9e94-138378aadbba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gwt-debug-project']</value>
      <webElementGuid>7bcd8375-b135-4a87-b6dd-c05d7d4ab993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>90df8ba8-795f-4ad8-a41f-868c83b871af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[1]/following::select[1]</value>
      <webElementGuid>8bff3af0-fa30-4ae6-b758-575e2664f8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Details'])[1]/following::select[1]</value>
      <webElementGuid>9505254a-2b4d-4b26-ad46-d488665ce125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[1]/preceding::select[1]</value>
      <webElementGuid>631a6fbf-9289-49e4-93ea-00c97b0eef8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target'])[1]/preceding::select[2]</value>
      <webElementGuid>339cbcb6-87a3-4e7a-9cb1-450f51f82948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>eafaad5d-83e5-491b-ab56-79932ba65160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gwt-debug-project' and (text() = 'Select an optionIO - TestProjectIO - TestProjectIO - ToluTest ProjectIO - IOPROD_ProjectIO - IOProject' or . = 'Select an optionIO - TestProjectIO - TestProjectIO - ToluTest ProjectIO - IOPROD_ProjectIO - IOProject')]</value>
      <webElementGuid>17b07b7c-2aa0-490c-adfb-3e6027139e39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
