<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an optionTestTest2</name>
   <tag></tag>
   <elementGuidId>75fdc95a-11e5-4a5a-be36-a1de6fef7618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-subProject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gwt-debug-subProject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-subProject</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17b1e0cf-8cb5-40a1-936c-680a57fbb96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-mandatory c-simple-ddl c-simple-ddl-width</value>
      <webElementGuid>6d7a06c2-63c0-48bf-89ae-e11b5805b743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-subProject</value>
      <webElementGuid>e093ee11-0a97-4482-a72a-e5f76bc7dd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an optionTestTest2</value>
      <webElementGuid>db481bbc-6005-4f0a-a2fb-05f4bf96aaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-subProject&quot;)</value>
      <webElementGuid>18ef789a-380c-4f65-a3bd-eba48dafc759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gwt-debug-subProject']</value>
      <webElementGuid>6bef60d3-4ac3-4f08-95e0-5b5a9916343c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>96186199-fcf4-47ce-842a-c1de73a75ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Project'])[1]/following::select[1]</value>
      <webElementGuid>8cc1940e-dfa8-4c9c-8294-7f1b66c1f7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target'])[1]/following::select[2]</value>
      <webElementGuid>46a4045e-57b7-47de-9e57-470442b0e973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[2]/preceding::select[1]</value>
      <webElementGuid>99b7c290-3af4-4999-a0d7-0025e0142adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Type'])[1]/preceding::select[2]</value>
      <webElementGuid>8df966a8-df3b-4f1a-be7a-1bae1bb1dc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>da016fcd-ae5e-4613-885f-73176697de64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gwt-debug-subProject' and (text() = 'Select an optionTestTest2' or . = 'Select an optionTestTest2')]</value>
      <webElementGuid>459065c1-b3ca-4c01-8699-f5890ef25f30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
