<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an optionIO - ToluTest Projec_2791f5</name>
   <tag></tag>
   <elementGuidId>4c742a11-aee1-4789-90c6-14e29b704ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-project</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gwt-debug-project']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-project</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ecae612e-acaa-4770-960e-3d3140d48d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-mandatory c-simple-ddl c-simple-ddl-width</value>
      <webElementGuid>924c2281-348f-4357-96fa-37ce82d9286d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-project</value>
      <webElementGuid>458716ae-d909-4525-8089-e9f1d66a12f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an optionIO - ToluTest ProjectIO - IOPROD_ProjectIO - IOProject</value>
      <webElementGuid>ec0bae53-390f-46d5-9789-1bfa36d8e4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-project&quot;)</value>
      <webElementGuid>8e70ea86-1250-4580-9970-e9b5d0995e2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gwt-debug-project']</value>
      <webElementGuid>83824f9f-8eeb-4f31-a684-20636bfcaa79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>d7301837-40f3-4352-947f-6ded4d1a8420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[1]/following::select[1]</value>
      <webElementGuid>3a76b4c1-db4f-4cd9-ba2d-f23be98a7551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Details'])[1]/following::select[1]</value>
      <webElementGuid>9167e444-378e-44ad-bdd5-d8f26c6ff152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[1]/preceding::select[1]</value>
      <webElementGuid>977c42e4-7ff0-4a1b-b62a-8e9ea5272a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target'])[1]/preceding::select[2]</value>
      <webElementGuid>c8e4f64c-93cb-4b3e-af54-6565c0e8a1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3d7cc1ec-d7c6-4a7b-8bd1-c1e8acffec3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gwt-debug-project' and (text() = 'Select an optionIO - ToluTest ProjectIO - IOPROD_ProjectIO - IOProject' or . = 'Select an optionIO - ToluTest ProjectIO - IOPROD_ProjectIO - IOProject')]</value>
      <webElementGuid>116d7b3b-d200-4eeb-8e16-6519009968e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
