<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Publish</name>
   <tag></tag>
   <elementGuidId>49f5797b-d389-49a4-842a-76884682e09e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.c-button-pad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//Button[text()='Publish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Publish&quot;s] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb58a92c-3a66-4296-a305-b3ef9bded9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c9eaa47-c5ff-4e0f-8720-611685d83742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary c-button-pad</value>
      <webElementGuid>7999d765-62ed-4092-8f6c-2cdf97d247ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publish</value>
      <webElementGuid>8d80d57d-33f5-4ea6-987c-6ffe550a0541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageBody&quot;)/div[2]/div[1]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;pt-15&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body c-publish-detail-body&quot;]/div[5]/table[@class=&quot;c-publish-filter&quot;]/tbody[1]/tr[1]/td[1]/button[@class=&quot;btn btn-primary c-button-pad&quot;]</value>
      <webElementGuid>7cea9b8c-bbd6-431b-8db3-3b85f134b7ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>c68d6711-1d0c-40ef-b38a-f9497f7c5511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div[5]/table/tbody/tr/td/button</value>
      <webElementGuid>a527de26-7da6-4994-afee-b3269e37c380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Type'])[1]/following::button[1]</value>
      <webElementGuid>08be214a-5457-43e1-83f3-92304b85ba22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[2]/following::button[1]</value>
      <webElementGuid>74a7fcdb-91c2-48df-b3de-a438c3deae3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Status'])[1]/preceding::button[1]</value>
      <webElementGuid>5cde14a4-f70f-4292-b82c-66ef1d79e23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::button[1]</value>
      <webElementGuid>75e117ae-44e4-496b-a714-1550056c4b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>2645b266-9263-479a-9a6f-403e838aa661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Publish' or . = 'Publish')]</value>
      <webElementGuid>a5c23c6b-bd09-41ec-ad80-41e7abee81ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
