<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an optionTestTest</name>
   <tag></tag>
   <elementGuidId>6297abdf-ada8-4e50-8153-b3e4ae83cd02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-subProject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gwt-debug-subProject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-subProject</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8fcf07e5-4758-4ebe-a162-596b9cec0693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-mandatory c-simple-ddl c-simple-ddl-width</value>
      <webElementGuid>45ddf9c5-1d72-47de-82eb-8a218605f00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-subProject</value>
      <webElementGuid>5f2287d5-e625-4b2c-831a-be766b1792e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an optionTestTest</value>
      <webElementGuid>d82611d8-f8a6-49ab-90d8-92751d0ede30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-subProject&quot;)</value>
      <webElementGuid>e7388cf0-fc7b-4cf1-89c9-d328215aa28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gwt-debug-subProject']</value>
      <webElementGuid>04b3d360-5e3e-4bf1-aee1-31e8b2b83068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>40fba360-1b52-4929-b9e1-11b0956ed7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Project'])[1]/following::select[1]</value>
      <webElementGuid>2e848cc6-9702-4116-8e43-e7055a28da88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target'])[1]/following::select[2]</value>
      <webElementGuid>cddb12ea-a8d4-47b6-92f9-235d3e041850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[2]/preceding::select[1]</value>
      <webElementGuid>838d2625-fb23-4b2e-89e2-8ed7fabbe538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Type'])[1]/preceding::select[2]</value>
      <webElementGuid>bb1eb0ff-f589-40b2-9774-433e1c0268e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td/div/div/select</value>
      <webElementGuid>2ed24f27-9bf8-42a7-a8dd-35df1892600c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gwt-debug-subProject' and (text() = 'Select an optionTestTest' or . = 'Select an optionTestTest')]</value>
      <webElementGuid>d5b21518-3f0d-42a8-830f-c7540d617aa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
