<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Network_Service</description>
   <name>td_ALP_TO_ANY</name>
   <tag></tag>
   <elementGuidId>144753b0-4e59-470d-a7cf-361bc9b6c3ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[text()='ALP_TO_ANY'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
