<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Link_Prod_Project</name>
   <tag></tag>
   <elementGuidId>d232255c-9cf0-4354-8ce1-67284d286858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toparea']/div/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a.c-inline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Link_Prod_Project&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>547c9d56-6b6a-47d3-83be-9c77afe60ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inline</value>
      <webElementGuid>2ea834e0-2305-4ac3-b633-a1188cb16519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Link_Prod_Project</value>
      <webElementGuid>16326f1d-cfcf-4455-86eb-12330fcfc51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link_Prod_Project</value>
      <webElementGuid>3a85d476-4939-4d88-a9c9-ea127bdc9b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toparea&quot;)/div[@class=&quot;indentPageInfo cpmTopPanelHeader_1&quot;]/div[1]/ul[@class=&quot;breadcrumb&quot;]/li[3]/a[@class=&quot;c-inline&quot;]</value>
      <webElementGuid>81c458ef-9139-471f-9f88-2bfee2c26973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toparea']/div/div/ul/li[3]/a</value>
      <webElementGuid>fe3e0947-73ec-4b0f-bc6e-544398d5e274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Link_Prod_Project')]</value>
      <webElementGuid>31444c7e-de9e-4d1f-8f1b-8b734ce79a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINK'])[1]/following::a[1]</value>
      <webElementGuid>b02a3a11-4aba-49cd-9c67-313d89e4fe36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>160edf19-a054-4cf4-86d5-2f934c2150f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test - Version 4(work in progress)'])[1]/preceding::a[1]</value>
      <webElementGuid>0ab9ac00-0476-4e0a-a1b8-50a71bb7b1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate'])[2]/preceding::a[2]</value>
      <webElementGuid>32c17ccc-a0bb-4244-baa1-46bd55b4f1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link_Prod_Project']/parent::*</value>
      <webElementGuid>2c2cdb8d-3336-4cbb-b9f4-61d9aaeeb53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>9974e41f-6455-4921-9630-4ae8c9b32678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Link_Prod_Project' and (text() = 'Link_Prod_Project' or . = 'Link_Prod_Project')]</value>
      <webElementGuid>0e6c5343-7a30-4f39-9475-af231936b4d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
