<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Validate</name>
   <tag></tag>
   <elementGuidId>6b5ea80c-847c-4c8a-b5ce-f6447616cc78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='propsarea']/div/div[3]/table/tbody/tr/td/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.breadcrumb.pipe-separated-links > li:nth-of-type(4) > a.c-inline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Validate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7881f51a-f8b8-4294-91dd-820b238be0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inline</value>
      <webElementGuid>7ab379f7-4021-4b01-ae55-803dee8acce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Validate</value>
      <webElementGuid>a00b15a1-1a68-4852-9254-82c4a447190f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validate</value>
      <webElementGuid>d8d30b8d-2109-4fe4-91b8-abfa3acf022e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propsarea&quot;)/div[@class=&quot;cpmBottomPanelHeaderSansLine&quot;]/div[@class=&quot;col-md-4 text-right&quot;]/table[@class=&quot;pull-right&quot;]/tbody[1]/tr[1]/td[@class=&quot;actionLinkArea&quot;]/ul[@class=&quot;breadcrumb pipe-separated-links&quot;]/li[4]/a[@class=&quot;c-inline&quot;]</value>
      <webElementGuid>55e0776d-7f32-4ca9-9475-99e8496a2af8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propsarea']/div/div[3]/table/tbody/tr/td/ul/li[4]/a</value>
      <webElementGuid>c1f5e476-ee87-4f33-95f2-6a809b90865e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Validate')]</value>
      <webElementGuid>d1191638-71d1-4ef7-a012-5b89746b2ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto-fix'])[1]/following::a[1]</value>
      <webElementGuid>e45f9eec-0024-4282-a3f2-e160a24f00a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only Errors'])[1]/following::a[2]</value>
      <webElementGuid>0250ee00-18ea-4a69-afe4-f6f76c19b214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge To Main Project'])[1]/preceding::a[1]</value>
      <webElementGuid>4b5b118d-037e-444f-9cc5-f83bd4c8ca65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::a[2]</value>
      <webElementGuid>6cb6b6dd-f2be-46c9-9906-ae70e4d13ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[4]/a</value>
      <webElementGuid>46d9ecc5-a9e9-4efa-8123-43a5a9629273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Validate' and (text() = 'Validate' or . = 'Validate')]</value>
      <webElementGuid>849470b3-f622-4efa-93c6-c0ef691f0a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
