<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gibtelecom - Pooja_DemoEdited 22052024 _a8718a</name>
   <tag></tag>
   <elementGuidId>e219543f-fc04-4a34-bcb9-d390fe4e05c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.projects-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Gibtelecom - Pooja_DemoEdited: 22/05/2024 \(Me: 22/05/2024\)$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af66175e-8b73-4e79-8d60-3a9cc3645c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>projects-list</value>
      <webElementGuid>9ea0285b-fee5-4741-b7a9-eb1dcafe9b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gibtelecom - Pooja_DemoEdited: 22/05/2024 (Me: 22/05/2024)</value>
      <webElementGuid>7bc830f3-e660-48e0-b739-4d1aaa395bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftarea&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body c-panel-reduce-padding&quot;]/div[@class=&quot;projects-list-outer auto-height bottom-margin-20&quot;]/div[@class=&quot;projects-list-inner&quot;]/div[@class=&quot;projects-list&quot;]</value>
      <webElementGuid>1d94559a-59af-4471-a1db-5c01fa542234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>883199c8-9989-4c44-9a52-05f8d581aa54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects Available'])[1]/following::div[4]</value>
      <webElementGuid>4f8c8b42-d4e9-48de-8c26-2392815fd66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>0b5c2964-dd77-49cf-8b21-285cfad4ff53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gibtelecom - Pooja_DemoEdited: 22/05/2024 (Me: 22/05/2024)' or . = 'Gibtelecom - Pooja_DemoEdited: 22/05/2024 (Me: 22/05/2024)')]</value>
      <webElementGuid>311d32df-6a47-424c-90ba-f4d2d1a9bd5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
