<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_IO - IOPROD_Project</name>
   <tag></tag>
   <elementGuidId>3f441ddf-47b9-4d1f-a407-30f0572a1f67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[(text() = 'IO - IOPROD_Project' or . = 'IO - IOPROD_Project')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;IO - IOPROD_Project&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>c85e94fa-26d1-4d37-bdb0-1a72ba449cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>project-name</value>
      <webElementGuid>d07e64c0-21ec-409d-a1ef-9a8a8b3290b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IO - IOPROD_Project</value>
      <webElementGuid>46664aea-38fb-474a-a358-9e75abe1b1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftarea&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body c-panel-reduce-padding&quot;]/div[@class=&quot;projects-list-outer auto-height bottom-margin-20&quot;]/div[@class=&quot;projects-list-inner&quot;]/div[@class=&quot;projects-list&quot;]/div[@class=&quot;projects-right&quot;]/h4[@class=&quot;project-name&quot;]</value>
      <webElementGuid>0cea4d38-6c2f-4a88-afa8-98f0f386e843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'IO - IOPROD_Project' or . = 'IO - IOPROD_Project')]</value>
      <webElementGuid>257b13e7-682b-4ee5-a1f2-f39c36e7a6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 18/06/2024 (Me: 18/06/2024)'])[1]/following::h4[1]</value>
      <webElementGuid>490e3f24-6e56-430a-8aaf-7300d6bc7faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IO - ToluTest Project'])[1]/following::h4[1]</value>
      <webElementGuid>a47cee0b-3b9b-48d1-a65d-48dcc025d8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 15/05/2024 (Me: 15/05/2024)'])[1]/preceding::h4[1]</value>
      <webElementGuid>799159c8-bc66-4908-a155-fb6b5ca3141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IO - IOProject'])[1]/preceding::h4[1]</value>
      <webElementGuid>94fd907f-1e0c-4372-a524-fec23410396e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IO - IOPROD_Project']/parent::*</value>
      <webElementGuid>af002a1c-10bb-4236-a45a-fff206b46181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div[2]/div[2]/h4</value>
      <webElementGuid>7e380d3f-cd16-4446-9a66-07f5cab1a069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/h4</value>
      <webElementGuid>cc452876-a9de-4d27-be03-dd90f3dc9742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 29/05/2024 (Me: 20/05/2024)'])[1]/following::h4[1]</value>
      <webElementGuid>670441d2-af56-415d-aaa2-a7672167e493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 29/05/2024 (Me: 29/05/2024)'])[1]/following::h4[1]</value>
      <webElementGuid>c2445861-91d4-4551-87be-4eeee112173c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div[4]/div[2]/h4</value>
      <webElementGuid>1bc9d3eb-fb80-4d15-8178-8d5d462afacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 16:52 (Me: 16:52)'])[1]/following::h4[1]</value>
      <webElementGuid>db649fb5-edee-4105-963b-d7b6f3c1c839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/h4</value>
      <webElementGuid>37774873-248a-4161-9f36-7d4586468527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div/div[2]/h4</value>
      <webElementGuid>b96e14a4-7465-46c0-bc3b-a37f6b040b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects Available'])[1]/following::h4[1]</value>
      <webElementGuid>2133f1b7-aa12-4d71-a354-9d753860a5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>5c50b2e9-a8b9-4e69-ae71-73c3f71d190b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
