<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_IO - IOPROD_Project</name>
   <tag></tag>
   <elementGuidId>3f441ddf-47b9-4d1f-a407-30f0572a1f67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div[2]/div[2]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;IO - IOPROD_Project&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>456a9c6d-3943-41ce-bf69-6a63415ea97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>project-name</value>
      <webElementGuid>2f6dfaa5-28be-4c71-9e8f-9d325cccbf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IO - IOPROD_Project</value>
      <webElementGuid>b6c7091a-28f9-49ee-8427-8f719cd6c816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftarea&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body c-panel-reduce-padding&quot;]/div[@class=&quot;projects-list-outer auto-height bottom-margin-20&quot;]/div[@class=&quot;projects-list-inner&quot;]/div[@class=&quot;projects-list&quot;]/div[@class=&quot;projects-right&quot;]/h4[@class=&quot;project-name&quot;]</value>
      <webElementGuid>afc81601-6998-40f9-a23d-95b1dc609975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div[2]/div[2]/h4</value>
      <webElementGuid>ccb7ed15-ab19-4dbe-8d0f-56fab6cb6aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 29/05/2024 (Me: 20/05/2024)'])[1]/following::h4[1]</value>
      <webElementGuid>6192c968-f942-40e7-ad56-7196eb79ee28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IO - ToluTest Project'])[1]/following::h4[1]</value>
      <webElementGuid>fec51abd-4c0e-4d85-a64e-f9a940adcc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 15/05/2024 (Me: 15/05/2024)'])[1]/preceding::h4[1]</value>
      <webElementGuid>dba5d4d4-2547-45b2-8cfe-b2b8ef171637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IO - IOProject'])[1]/preceding::h4[1]</value>
      <webElementGuid>13498e19-2576-4165-be60-8031380d4895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IO - IOPROD_Project']/parent::*</value>
      <webElementGuid>15e6a001-ea15-4f51-b0f0-de6788d2e608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/h4</value>
      <webElementGuid>2ae706fb-efd3-4f17-a804-7f3d5bd80491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'IO - IOPROD_Project' or . = 'IO - IOPROD_Project')]</value>
      <webElementGuid>eab68221-0ecf-44f9-8938-e0ae62c58a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 29/05/2024 (Me: 29/05/2024)'])[1]/following::h4[1]</value>
      <webElementGuid>c2445861-91d4-4551-87be-4eeee112173c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div[4]/div[2]/h4</value>
      <webElementGuid>1bc9d3eb-fb80-4d15-8178-8d5d462afacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited: 16:52 (Me: 16:52)'])[1]/following::h4[1]</value>
      <webElementGuid>db649fb5-edee-4105-963b-d7b6f3c1c839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/h4</value>
      <webElementGuid>37774873-248a-4161-9f36-7d4586468527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div[2]/div/div/div/div[2]/h4</value>
      <webElementGuid>b96e14a4-7465-46c0-bc3b-a37f6b040b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects Available'])[1]/following::h4[1]</value>
      <webElementGuid>2133f1b7-aa12-4d71-a354-9d753860a5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>5c50b2e9-a8b9-4e69-ae71-73c3f71d190b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
