<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ae7cd593-c8e7-4eb2-8dff-7d0ab7cc8324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gwt-debug-liveRadioStyle']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-liveRadioStyle > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-liveRadioStyle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ea651bf2-b44b-4e28-ba14-ed6cfdf1d0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>skin/img/radio_chk0.gif</value>
      <webElementGuid>b55a92b9-ebe2-4f4a-a9b1-0f5111dd7eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-liveRadioStyle&quot;)/img[1]</value>
      <webElementGuid>ff1f7a6a-418f-4ec8-85cb-96e2b549cde3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='gwt-debug-liveRadioStyle']/img</value>
      <webElementGuid>b813b091-74c9-4e6e-8a63-0609e55b1d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>51a5f393-0c32-433e-8d5a-c52ecd5034ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'skin/img/radio_chk0.gif']</value>
      <webElementGuid>36516fc7-3d29-4f5d-b3b4-f8e928c22b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
