<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Server Name_gwt-debug-</name>
   <tag></tag>
   <elementGuidId>605598fd-3fcc-4112-9f92-e875da9d3c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='gwt-debug-'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > div > div.row > div.col-md-6 > div.col-md-9 > div.c-bottom-margin > div > div > #gwt-debug-</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tabpanel >> internal:role=textbox >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee0581ec-5d4b-40fa-9bc6-f7a30d2248ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7adaf308-7db6-43ce-a9aa-564f6b023a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-textbox</value>
      <webElementGuid>efbbced3-ecbf-4b9d-a736-d4a08433030a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-</value>
      <webElementGuid>276c402e-53ad-4195-9440-06f66aa4b876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>8bbe1c81-7810-478c-91a1-126799ba6472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1dbe8e5-093a-4529-b4b2-8f911cca1ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cpm-whole-body&quot;]/div[@class=&quot;popupPanel&quot;]/div[1]/table[1]/tbody[1]/tr[@class=&quot;dialogMiddle&quot;]/td[@class=&quot;dialogMiddleCenter&quot;]/div[@class=&quot;dialogMiddleCenterInner dialogContent&quot;]/div[@class=&quot;targetPopup&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/div[1]/table[@class=&quot;gwt-TabPanel&quot;]/tbody[1]/tr[2]/td[1]/div[@class=&quot;gwt-TabPanelBottom&quot;]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;c-bottom-margin&quot;]/div[1]/div[1]/input[@id=&quot;gwt-debug-&quot;]</value>
      <webElementGuid>040cb6ba-eec7-4ec2-a6da-28efc9fc5698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='gwt-debug-'])[6]</value>
      <webElementGuid>c854d780-c0a4-426b-9113-765d1f4c5920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>3cefc8af-2dee-421c-8465-e9a5dad0f06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'gwt-debug-']</value>
      <webElementGuid>41c8f28d-6ec5-4d1e-a5d4-42cc1cb1b9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='gwt-debug-'])[3]</value>
      <webElementGuid>410d0d1a-06ce-4798-b076-f4a6746fc777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>82c1379e-6f57-4f23-9401-3c2ac8130ba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
