<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Project name_gwt-debug-projectName</name>
   <tag></tag>
   <elementGuidId>160e6683-739b-430a-b400-28c499a018a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-projectName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gwt-debug-projectName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-debug-projectName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2df75405-4edb-413e-a37d-82ce21b61102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de6bdeb0-4ac5-450d-8636-fc08f651e120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-textbox c-mandatory</value>
      <webElementGuid>d352d040-15e5-4ad7-9867-f6d16bd18807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-projectName</value>
      <webElementGuid>fc8b6e77-3755-489b-9d59-676f62c93e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>28e38e97-49e5-46a7-95d2-1817d64c934a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc3203a2-f5d3-4f87-ac6c-220dd2ce9993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-projectName&quot;)</value>
      <webElementGuid>3744a303-a6e4-4228-b53a-d124a3d03b22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gwt-debug-projectName']</value>
      <webElementGuid>bc175554-cefe-454d-89e1-e7b804927b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>41f7a7a8-5565-4d79-b5ff-ed596ac55de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'gwt-debug-projectName']</value>
      <webElementGuid>0ec9225d-3b73-4b43-ac23-cd0215cffaf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
