<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Existing</name>
   <tag></tag>
   <elementGuidId>631ce597-3989-480b-8513-a05d496b75fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#existingpalette</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '#existing' and @id = 'existingpalette' and (text() = 'Existing' or . = 'Existing')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Existing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>712da90c-1d56-4996-8834-f386a16c12c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#existing</value>
      <webElementGuid>418aea63-8f4e-4970-b00c-56f5167733a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>existingpalette</value>
      <webElementGuid>d3f87ec7-5f7d-48f5-a997-b312604449d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>73c8af40-52c2-42e9-a31b-863afef4d51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Existing</value>
      <webElementGuid>89863e3c-948f-4bf6-a248-176b1cac93e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingpalette&quot;)</value>
      <webElementGuid>8356a87e-f655-4251-93fd-527782991012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#existing' and @id = 'existingpalette' and (text() = 'Existing' or . = 'Existing')]</value>
      <webElementGuid>3a57ea9c-2c1c-4b6f-a634-4a96ecb7cbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[2]/following::a[1]</value>
      <webElementGuid>b072aebe-b17e-4899-9233-ef9583a1bf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/following::a[2]</value>
      <webElementGuid>cc1df42c-588c-450b-be7e-dac1c2ee83d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::a[1]</value>
      <webElementGuid>81a8d5be-78f8-4b16-ad8f-142947dcf58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help text goes here'])[1]/preceding::a[1]</value>
      <webElementGuid>f79cfa49-22e1-4409-97e0-489553900588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Existing']/parent::*</value>
      <webElementGuid>50a61dee-4462-4cd9-8b01-5407f6ca6ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='existingpalette']</value>
      <webElementGuid>b990fbaa-650b-4e22-81dd-0dd7fa4c07a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftarea']/div[2]/div/div/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>5421a3fc-e52d-4a3b-987c-e3b6e5ee0ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Existing')]</value>
      <webElementGuid>d5cb34a9-bbfc-4540-a1ff-1e3c551ebf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#existing')]</value>
      <webElementGuid>4020ed77-2f7f-40ff-9754-c3ebab1c43b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>fa85d3cf-6a3a-40b3-bd84-a2174bbe17b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
