<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__dhxcombo_select_img_1</name>
   <tag></tag>
   <elementGuidId>06d4a602-9801-49d2-a925-1f808f479b57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='recordView']/div/div[6]/div/div/div/div/div[2]/span/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(6) > div > .dhxform_base_nested > .dhxform_base > .dhxform_item_label_top > .dhxform_control > span > .dhxcombo_dhx_skyblue > .dhxcombo_select_button > .dhxcombo_select_img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>abb2d9f9-420e-4621-be83-64e5fc5a7c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxcombo_select_img</value>
      <webElementGuid>4b59d449-cbbb-4877-98fc-55af0affb348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recordView&quot;)/div[@class=&quot;dhxform_base&quot;]/div[@class=&quot;block_dhxform_item_label_top c-form-field&quot;]/div[@class=&quot;dhxform_obj_dhx_skyblue dhxform_block&quot;]/div[@class=&quot;dhxform_base_nested in_block&quot;]/div[@class=&quot;dhxform_base&quot;]/div[@class=&quot;dhxform_item_label_top&quot;]/div[@class=&quot;dhxform_control&quot;]/span[1]/div[@class=&quot;dhxcombo_dhx_skyblue&quot;]/div[@class=&quot;dhxcombo_select_button&quot;]/div[@class=&quot;dhxcombo_select_img&quot;]</value>
      <webElementGuid>1b4fb58a-29d9-41b5-b503-f32584081664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[6]/div/div/div/div/div[2]/span/div/div/div</value>
      <webElementGuid>c3ae2887-837f-45b8-8961-12404d50aea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[2]/span/div/div/div</value>
      <webElementGuid>dfc9f082-3bb7-4fa2-9d0e-07ada1f0a2aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
