<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dhxId_aDjwK651GXMZ</name>
   <tag></tag>
   <elementGuidId>83937925-cf41-4f74-a657-2dc406f08532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Product Group']//following::div//input)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dhxId_aDjwK651GXMZ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product Group*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ef98983-6786-4093-a3e4-7cc89711d6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d5e9262-6829-4ed9-aa78-6ece196cdd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxcombo_input</value>
      <webElementGuid>601d1bbc-9c42-485d-b8b3-44082eaa4003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>02a9b1ef-9f78-4ec5-99ed-10025f9dae90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_aDjwK651GXMZ</value>
      <webElementGuid>2c3d3a18-b016-4da5-9d24-a75b18a43951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>893e5a0e-4120-42cc-9dc0-75c3325b2986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please select</value>
      <webElementGuid>73e923b4-b346-4ff9-bbbc-5f0ebe75ba7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_aDjwK651GXMZ&quot;)</value>
      <webElementGuid>08149095-7a2f-406d-83c2-171ea06089b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_aDjwK651GXMZ']</value>
      <webElementGuid>4f3d152d-8de9-4154-8a59-49e206daa309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div[5]/div/div/div/div/div[2]/span/div/input</value>
      <webElementGuid>7692b510-3696-4953-9815-1fc31f9c2665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/span/div/input</value>
      <webElementGuid>065996df-89ad-40ab-ba57-dccf8b5c4097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dhxId_aDjwK651GXMZ' and @placeholder = 'Please select']</value>
      <webElementGuid>4464ffc1-6c93-4f25-8686-e543f50f1fed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
