<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Product Description</name>
   <tag></tag>
   <elementGuidId>319f2f3b-f45e-4a69-9a7c-87aa85cc658e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_sZKtyLxUaaQz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Product Description']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product Description*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d469027-6dac-4a52-8f3e-830945e161c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>e0bc5484-2dae-4a1a-946e-bce652f6f044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Product Description</value>
      <webElementGuid>fa21eebf-57c9-495d-9448-47d55f6b2805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_sZKtyLxUaaQz</value>
      <webElementGuid>9cd1fc17-4ff8-485c-a18c-6a8be7156b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>b8aa7f92-ea61-4299-8d50-a9cfcc993c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c528fa62-2a4a-4212-bebd-b3e69ae7ff64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>53210096-37a1-4195-88d9-64a264cf97c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_sZKtyLxUaaQz&quot;)</value>
      <webElementGuid>31958abd-5fc3-48d6-8323-9fc0737e4596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_sZKtyLxUaaQz']</value>
      <webElementGuid>19e943c3-1f44-4896-9e8d-517c4476d235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[4]/div/div/div/div/div[2]/input</value>
      <webElementGuid>5a72615f-7758-431f-9076-e25d1d104af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>37a843e5-ef4c-40c7-8b52-c511c42c1aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_sZKtyLxUaaQz' and @type = 'TEXT']</value>
      <webElementGuid>e701157a-3604-4aa5-9902-fd4c1d940891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_YM4NSKW1Z7FO']</value>
      <webElementGuid>3f99fa02-baa4-4542-801d-46439f2d207b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_YM4NSKW1Z7FO' and @type = 'TEXT']</value>
      <webElementGuid>77816dde-2ddf-4b58-811c-02e71c5b1e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_S12hRetMEBLq']</value>
      <webElementGuid>d0b865a9-d678-4a48-b17f-2e8c0d7aac4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_S12hRetMEBLq' and @type = 'TEXT']</value>
      <webElementGuid>bbbc5442-f53e-4270-ab9b-3fea5a69b332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
