<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Gl 11 Cost</name>
   <tag></tag>
   <elementGuidId>d5a5e30b-27df-4400-92c9-d4fb32e9627e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_1PqmQqrqtQBc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Gl 11 Cost']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gl 11 Cost*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8565c4da-69b2-488a-9d82-1821ab8c8e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>5dad0584-15d4-416b-8a14-5f212f627098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gl 11 Cost</value>
      <webElementGuid>b9cae884-18ca-4131-a106-401cdb9aa0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_1PqmQqrqtQBc</value>
      <webElementGuid>1cd70b16-be33-4c52-8091-02dfb41c5517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>0fce1f25-0142-478f-b1e5-f25b423ab6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>b4f81df5-d405-4385-9b1c-05bd37a96fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>6672eca6-cef8-4f2a-8c8c-cf87da3e5480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_1PqmQqrqtQBc&quot;)</value>
      <webElementGuid>d88fefdc-a599-4526-b321-4f1d7271c308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_1PqmQqrqtQBc']</value>
      <webElementGuid>fcabc38c-c441-44ea-8680-75ca080f68c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>d87466fd-f4e1-4d60-862c-9614722422e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>0888eb2f-4360-4504-af18-90ea7e2915ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Cost' and @id = 'dhxId_1PqmQqrqtQBc' and @type = 'TEXT']</value>
      <webElementGuid>3a99b725-2a4e-4849-84c6-e554da46412d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_BxcPwu5k4EPe']</value>
      <webElementGuid>1b187cf4-9b7b-4409-a374-765e46bc806b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Cost' and @id = 'dhxId_BxcPwu5k4EPe' and @type = 'TEXT']</value>
      <webElementGuid>0d6d18af-9f70-4e50-8d4e-c847a6c9aabd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
