<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dhxId_BFOrI7OMyFHo</name>
   <tag></tag>
   <elementGuidId>e7451018-92ee-47ce-a04b-4bc4c3797cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_BFOrI7OMyFHo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Service Type']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Service Type*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da125a90-459f-428d-8e20-0ed6baf75261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d016a9f-264f-4ced-883b-2f1640952e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxcombo_input</value>
      <webElementGuid>d92b50cc-f452-4628-8a9b-3038bb61e5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1de8a893-56d6-43f7-8c60-f9d3e87d541b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_BFOrI7OMyFHo</value>
      <webElementGuid>0e6cb3b7-cc12-4de5-a18f-259accd9a546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f8e9993b-6ced-45c2-8c0c-e932987a17f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please select</value>
      <webElementGuid>00c629d1-5ae1-4523-a629-34f9e69b09a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_BFOrI7OMyFHo&quot;)</value>
      <webElementGuid>2016c61f-94bc-4b58-b6bd-95101dc8676e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_BFOrI7OMyFHo']</value>
      <webElementGuid>f090d2b0-87b1-49a8-b6bd-aeef116642c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[2]/div/div/div/div[2]/div[2]/span/div/input</value>
      <webElementGuid>74c03b84-f67d-4cf2-9e2b-02942f097197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/span/div/input</value>
      <webElementGuid>e8c70001-7b6b-4064-ab22-090b03b98077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dhxId_BFOrI7OMyFHo' and @placeholder = 'Please select']</value>
      <webElementGuid>496a64f5-8191-40ab-bbd9-b269cdf66550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
