<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dhxId_xxtHQVbGIcQK</name>
   <tag></tag>
   <elementGuidId>325fca70-a6a8-458e-92cf-c5b4a1a78b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_xxtHQVbGIcQK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Service Type']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Service Type*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fc445f8-1268-4e6e-bbc7-9dbad6189b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4140f5f-c72c-404f-80c7-635e3c23576f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxcombo_input</value>
      <webElementGuid>1c89d5e0-b095-4cc2-9dfb-0b7f4977f6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>99c3a7ee-69c3-45c4-9963-eda77d9f3963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_xxtHQVbGIcQK</value>
      <webElementGuid>1599bca9-30b4-47f6-9d4a-bb35d00bd672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>58d6d4c9-653d-4625-b025-e0227ae37a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please select</value>
      <webElementGuid>a083d3dc-26fe-4c0f-8fb1-5f4dec8b28c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_xxtHQVbGIcQK&quot;)</value>
      <webElementGuid>b99f0e05-15d4-4e58-a529-6e20f1a15b5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_xxtHQVbGIcQK']</value>
      <webElementGuid>b2d7d525-b3c9-4300-b306-4a8009e131a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[2]/div/div/div/div[2]/div[2]/span/div/input</value>
      <webElementGuid>0515f4f8-3847-4dce-9382-ae19a9b2aef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/span/div/input</value>
      <webElementGuid>39eae0be-af6d-47a3-9cf3-d4d645c3de9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dhxId_xxtHQVbGIcQK' and @placeholder = 'Please select']</value>
      <webElementGuid>830699d9-ba8a-4c9c-a53a-20bc7925fa57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
