<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Product Description</name>
   <tag></tag>
   <elementGuidId>319f2f3b-f45e-4a69-9a7c-87aa85cc658e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Product Description']//following::div//input)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dhxId_7GyFy1G6Twqk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product Description*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b4fb092-202f-4ed8-a208-e43789caaf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>b1fe5c01-93a8-4263-bef9-b29ee1cedef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Product Description</value>
      <webElementGuid>9b376bb6-d3cf-46a0-9d2d-d0f250519811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_7GyFy1G6Twqk</value>
      <webElementGuid>3135cdae-74e4-4289-b33d-810c6adabb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>3fdb106b-8f98-4cd5-9c52-8550d0ac89a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>790f10f1-13d5-42c5-b2bb-9cdf7b9a82aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>c30b57ec-5cb1-4f14-b5cd-4e3bbc72ca7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_7GyFy1G6Twqk&quot;)</value>
      <webElementGuid>84b5d638-0fd7-4fdf-8c41-d3bac4830e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_7GyFy1G6Twqk' and @type = 'TEXT']</value>
      <webElementGuid>1ccac4d2-3615-401e-839d-f5d34277384b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_7GyFy1G6Twqk']</value>
      <webElementGuid>d7a27f3a-f2ce-4f87-afb1-67e4ccb4b7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div[4]/div/div/div/div/div[2]/input</value>
      <webElementGuid>8834a44b-c781-4557-9b61-fce4cbaf4499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4e26132a-a989-4d3a-959f-bac5e652bbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_xW8CdMzfCnJJ' and @type = 'TEXT']</value>
      <webElementGuid>3d5837aa-e639-4bd9-84a4-1be91f1d1ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_xW8CdMzfCnJJ']</value>
      <webElementGuid>b43b9c57-ff5f-4f14-9d15-a7dcdad56e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_sZKtyLxUaaQz']</value>
      <webElementGuid>8429c9e3-940e-4794-b1af-758a37131150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_sZKtyLxUaaQz' and @type = 'TEXT']</value>
      <webElementGuid>9fb86dda-f6cc-479d-9727-192c566a6e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_YM4NSKW1Z7FO']</value>
      <webElementGuid>8f74bc7e-a17d-4399-be6d-fa4aa8e3db4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_YM4NSKW1Z7FO' and @type = 'TEXT']</value>
      <webElementGuid>46920d47-c334-4e1f-b7f2-0286d41bd6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_S12hRetMEBLq']</value>
      <webElementGuid>393235b4-a4d6-4ffe-be6f-f5bc922668f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Product Description' and @id = 'dhxId_S12hRetMEBLq' and @type = 'TEXT']</value>
      <webElementGuid>2929d6db-ad53-4640-bbaa-e25cd98aba16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
