<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dhxId_uRRkyLTqXRyX</name>
   <tag></tag>
   <elementGuidId>2a607a3b-d498-45d1-a638-28c42d6d7d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_uRRkyLTqXRyX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Currency']//following::div//input)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'dhxId_uRRkyLTqXRyX' and @placeholder = 'Please select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Currency*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34315cea-b800-4b87-9505-cdf02fb3aec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c74d8cc0-1a38-4f36-936a-9a413637849f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxcombo_input</value>
      <webElementGuid>5d475e1a-401d-4b2a-9c95-304652268ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>50b763a9-c227-4c6b-8ca5-799a1bbf7482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_uRRkyLTqXRyX</value>
      <webElementGuid>8fec035b-aef5-4bbf-9dc4-35ea738b867a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4919cbf4-c967-40a4-a440-7a1a1cc483e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please select</value>
      <webElementGuid>da3a15a3-7df9-473e-a2b4-69aa6537c669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_uRRkyLTqXRyX&quot;)</value>
      <webElementGuid>b73d8edd-ee76-4842-a2ac-59da0bf49952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_uRRkyLTqXRyX']</value>
      <webElementGuid>d960b7af-f785-4e60-8e00-584dcb0f9c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div/div/div/div/div/div[2]/div[2]/span/div/input</value>
      <webElementGuid>d7f2888c-de54-4738-906b-eeac50e0cad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>c96f0312-33d0-4751-9711-e4d64288d7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dhxId_uRRkyLTqXRyX' and @placeholder = 'Please select']</value>
      <webElementGuid>b9d62bb3-3f3f-4578-92f5-41136f83d717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
