<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Gl 11 Income</name>
   <tag></tag>
   <elementGuidId>1b0082f9-3c4d-4ebd-8a23-608aa341d1fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dhxId_yNc52FF1lq21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//label[text()='Gl 11 Income']//following::div//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gl 11 Income*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24f1c0e7-c247-4bd8-9a75-c8f91c4ae7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dhxform_textarea</value>
      <webElementGuid>531e5c18-f28d-4e5b-9802-7eb505c93047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gl 11 Income</value>
      <webElementGuid>5d396f33-dc2d-45d7-a1e2-f384b4a08fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dhxId_yNc52FF1lq21</value>
      <webElementGuid>fd85b3ee-9705-47ca-b5bb-a5f295e64917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>f0041eca-f9b3-4c68-88d7-7d34660823ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>c20c4297-8074-45f9-972d-2ecfaf2a8514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>5532907b-540e-4db0-a70b-1dcc4396443f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dhxId_yNc52FF1lq21&quot;)</value>
      <webElementGuid>7de6155c-23dc-484f-9b65-d6ab263dc14a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_yNc52FF1lq21']</value>
      <webElementGuid>6b6a7b4f-453d-4007-bebe-111c8a77431f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recordView']/div[2]/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>ab90adb0-5fbf-429a-9755-7361fb5d490e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div/div/div/div/div[2]/input</value>
      <webElementGuid>af15c4fa-51d6-460c-aa84-566761ef7f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Income' and @id = 'dhxId_yNc52FF1lq21' and @type = 'TEXT']</value>
      <webElementGuid>c1ddf0e5-467d-4ee7-8a5c-5fca0db4e6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dhxId_ItAAHkFtQEre']</value>
      <webElementGuid>32bd20e5-6683-40b3-8e3d-5dfeb13148ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Gl 11 Income' and @id = 'dhxId_ItAAHkFtQEre' and @type = 'TEXT']</value>
      <webElementGuid>5c1325e8-9ac5-4829-8712-9258bf3b2b6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
