<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CVLAN</name>
   <tag></tag>
   <elementGuidId>ad9c7118-6f55-4619-891b-86c59aa64538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td[title=&quot;CVLAN&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@title = 'CVLAN' and (text() = 'CVLAN' or . = 'CVLAN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;CVLAN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>78354100-5da9-4bbe-8208-89bef8334a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>669a3e7b-c042-43d4-868e-b756618931e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>f588a385-1527-4b79-914f-21353fefdda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>CVLAN</value>
      <webElementGuid>5d2a310d-7303-4844-ba58-07deb29cde2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CVLAN</value>
      <webElementGuid>a52072f9-829a-4b66-b1fa-56ca3a83f0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingGrid&quot;)/div[@class=&quot;objbox&quot;]/table[@class=&quot;obj row20px&quot;]/tbody[1]/tr[@class=&quot;ev_dhx_skyblue&quot;]/td[2]</value>
      <webElementGuid>0b72c8f3-c514-41d9-8b87-aaa215cb18e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existingGrid']/div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>d473f73e-1dc3-48d8-8492-c2b4bc108658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VLAN'])[1]/following::td[1]</value>
      <webElementGuid>0811e549-15ef-437c-bf9a-2c0be8d2a7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package'])[1]/following::td[11]</value>
      <webElementGuid>470a2bd6-e87d-43df-b51e-0d3a7ab6b7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Always'])[1]/preceding::td[4]</value>
      <webElementGuid>b5876ed0-2bc8-4c12-bf3c-7162a1547604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::td[5]</value>
      <webElementGuid>5866f5de-9d10-4023-bd09-4609f28cf2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CVLAN']/parent::*</value>
      <webElementGuid>77b0d74c-2dee-4ff4-855b-2a2bcfd60a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>9595b525-2d56-4433-b3b5-0f652d802dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'CVLAN' and (text() = 'CVLAN' or . = 'CVLAN')]</value>
      <webElementGuid>e2a51b4a-be19-4418-8cfe-15e3b4ec0e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
