<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_PKGDAM</name>
   <tag></tag>
   <elementGuidId>0e5fb810-7f60-4cd8-8414-e00dbaeb35ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td[title=&quot;PKGDAM&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='PKGDAM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;PKGDAM&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2ce65ed8-95ad-4303-970e-a65e08913450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>2953be48-fbeb-4f72-8096-55a1ed645409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>4e66b074-1a1c-44f8-8f2c-e9ebc1cb3085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PKGDAM</value>
      <webElementGuid>05146462-8118-46ad-8f73-94643e401109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PKGDAM</value>
      <webElementGuid>ad288de6-a33c-411d-a3dc-185365c30869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingGrid&quot;)/div[@class=&quot;objbox&quot;]/table[@class=&quot;obj row20px&quot;]/tbody[1]/tr[@class=&quot;ev_dhx_skyblue&quot;]/td[2]</value>
      <webElementGuid>93b51aeb-a647-4ee3-bd67-4518414c4f04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existingGrid']/div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>bf28b056-66fc-4856-8906-3cf7e89255a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::td[1]</value>
      <webElementGuid>e8337f1e-3632-4c5c-a720-f142476c654c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Specification'])[3]/following::td[50]</value>
      <webElementGuid>3e163e54-0f13-459a-8326-c48b05633150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Damage to infrastructure by a third party'])[1]/preceding::td[1]</value>
      <webElementGuid>6f47f48c-9930-4692-ad87-528140307b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::td[2]</value>
      <webElementGuid>05f9451d-4563-4549-94a5-6f73d7365cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PKGDAM']/parent::*</value>
      <webElementGuid>3df11b61-0f4e-4a8e-bb55-a1277c105505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>99f0f64a-64b5-42f1-b91f-481653506743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'PKGDAM' and (text() = 'PKGDAM' or . = 'PKGDAM')]</value>
      <webElementGuid>7e810b07-29f4-4e80-9a95-fa3f7421dbaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
