<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_gwt-debug-password_password</name>
   <tag></tag>
   <elementGuidId>8c6a8d12-3b23-4931-a374-a44afb83e643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gwt-debug-password_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gwt-debug-password_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>143c27fb-3f4a-4634-969b-2b49846ecf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>09c6cbb5-bf72-47d2-9542-e070f8df25c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-textbox c-mandatory</value>
      <webElementGuid>7118779e-7266-4ced-b63c-37bdfb7f1c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-debug-password_password</value>
      <webElementGuid>41d7c898-7adf-4213-8812-12addc8e3927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>7a807835-b758-4f90-ab78-f8fc0507460a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>24beb981-1b1e-4157-9a29-81361a6a6c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63168093-0542-4d0c-8ad6-0c4f7d3c24cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-debug-password_password&quot;)</value>
      <webElementGuid>f8e7bbd0-ddf5-4cf8-89a2-125716e9192a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gwt-debug-password_password']</value>
      <webElementGuid>37aa048f-6031-4284-89f0-15f695f961b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageBody']/div[2]/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>bd30d09f-b383-4b83-902b-dbd758ddd790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>71d46b8a-b04a-4dbc-a456-9d42efb36840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'gwt-debug-password_password' and @placeholder = 'Password']</value>
      <webElementGuid>23fa8d62-8e2a-49cc-8192-63fc3182d51a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
