<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Validate</name>
   <tag></tag>
   <elementGuidId>6b565e9f-d7a6-4c76-851b-7c536c67002c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a.c-inline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='propsarea']/div/div[3]/table/tbody/tr/td/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Validate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19288b49-5edd-4429-9df0-78c6ff9fb4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-inline</value>
      <webElementGuid>c0c7d096-c028-43c7-a154-bb85d9cd5606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Validate</value>
      <webElementGuid>cac3b473-6de4-438e-a545-68c18424ecd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validate</value>
      <webElementGuid>1e90c3d1-9eb5-4fd4-bf93-9bea435ef296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propsarea&quot;)/div[@class=&quot;cpmBottomPanelHeaderSansLine&quot;]/div[@class=&quot;col-md-4 text-right&quot;]/table[@class=&quot;pull-right&quot;]/tbody[1]/tr[1]/td[@class=&quot;actionLinkArea&quot;]/ul[@class=&quot;breadcrumb pipe-separated-links&quot;]/li[4]/a[@class=&quot;c-inline&quot;]</value>
      <webElementGuid>c04a7eb6-9534-4011-94bd-05663d950c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propsarea']/div/div[3]/table/tbody/tr/td/ul/li[4]/a</value>
      <webElementGuid>1d8bcd74-07d9-459b-87be-1f290d060100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Validate')]</value>
      <webElementGuid>21d264a9-f8d3-46f6-8f78-b0e17ac45f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto-fix'])[1]/following::a[1]</value>
      <webElementGuid>a115eb92-6a15-47eb-b1e5-4e4095adce9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only Errors'])[1]/following::a[2]</value>
      <webElementGuid>ffc9b275-d357-40dd-9232-52e7cc00ac9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge To Main Project'])[1]/preceding::a[1]</value>
      <webElementGuid>8bdd3704-c5a3-49e1-afe0-9c8c3f831abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::a[2]</value>
      <webElementGuid>0c534937-b4eb-4e5d-a99b-758e1d0e2747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>3114e7ab-d49b-41ee-8ce9-2b4d20e3ba6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Validate' and (text() = 'Validate' or . = 'Validate')]</value>
      <webElementGuid>beed0b15-dab4-4d1d-a971-f1af44c9248e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
